### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by HHonzik** [quasar098/limbos32#81]
On my system the keys spawn but they just slowly move to the top left. No idea why. Also all keys are the same color and image (key.png)
OS: Arch Linux x86_64 
Kernel: 6.8.7-arch1-2 
Uptime: 24 mins 
Packages: 1160 (pacman) 
Shell: bash 5.2.26 
Resolution: 1920x1080 
WM: wayfire 
Theme: Adwaita [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 5 3400G (8) @ 3.700GHz 
GPU: AMD ATI Radeon RX 6650 XT / 6700S / 6800S 
Memory: 4809MiB / 32003MiB

**Comment by quasar098** [comment]
on readme

![image](https://github.com/quasar098/limbos32/assets/70716985/67d7a5c0-c830-4895-bd8a-6ac244b17665)

the issue with linux is that there are so many different window/ui managers that it just seems like a nightmare to support all of them. also, i am on windows, and it seems like a huge hassle for me to set up a bunch of vms with common window managers

**Comment by quasar098** [comment]
> Also all keys are the same color and image

this has to be turned on by editing the python file (key.py line 71)

**Comment by unkn0wncvm1** [comment]
> on readme
> 
> ![image](https://private-user-images.githubusercontent.com/70716985/326317126-67d7a5c0-c830-4895-bd8a-6ac244b17665.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxNTUxODIsIm5iZiI6MTcxNjE1NDg4MiwicGF0aCI6Ii83MDcxNjk4NS8zMjYzMTcxMjYtNjdkN2E1YzAtYzgzMC00ODk1LWJkOGEtNmFjMjQ0YjE3NjY1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDIxNDEyMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI3MDhiNGZjOGY5M2NlMjNkZDRjYTFmMjhiNTc5ZDllZDg0NWFmNTA5OTZhMDEwYTM1NzNkZDhkODMxOGRhMjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-62r04UjF8GjbFcHy_i0bJBbqRuNrr1NJgZilb66KCE)
> 
> the issue with linux is that there are so many different window/ui managers that it just seems like a nightmare to support all of them. also, i am on windows, and it seems like a huge hassle for me to set up a bunch of vms with common window managers

you dont have to.just install it from the package manager and it will appear in the display manager

**Comment by nathm-bit** [comment]
Seems to work fine with 1 monitor on my system (Wayland, kwin). When i have two monitors connected it seems to try to spawn the keys in the middle of the monitors. Another issue seems to be that Plasma numbers the windows so it kinda breaks the game. Otherwise, works fine for me

![Screenshot_20240525_132000](https://github.com/quasar098/limbos32/assets/95842127/2d668743-b2ee-4d56-a427-a1802698af71)

OS: EndeavourOS Linux x86_64 
Kernel: 6.9.1-arch1-1 
Uptime: 42 mins 
Packages: 1858 (pacman), 7 (flatpak) 
Shell: zsh 5.9 
Resolution: 2560x1440 
DE: Plasma 6.0.4 
WM: kwin 
Theme: [Plasma], Breeze-Dark [GTK2], Breeze [GTK3] 
Icons: [Plasma], breeze-dark [GTK2/3] 
Terminal: konsole 
CPU: AMD Ryzen 7 5800X3D (16) @ 3.400GHz 
GPU: NVIDIA GeForce RTX 3060 Ti Lite Hash Rate 
Memory: 5223MiB / 32020MiB

**Comment by quasar098** [comment]
interesting

**Comment by HHonzik** [comment]
So it seems like some WM's just don't allow windows to move themself, I change my WM from wayfire to labwc (a obscure one to a more obscure one) and now it works.
